import type { ReactNode } from 'react'
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Cpu,
  FileSearch,
  HelpCircle,
  Layers,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Zap,
} from 'lucide-react'
import { useApi } from '../hooks/useApi'
import type { ComponentIntelligence } from '../types/api'
import { parseList, num } from '../utils/format'
import { StatusBadge } from '../components/common/StatusBadge'

export function EvidencePage({
  partId,
  source = 'active',
  onBack,
  onOpenComponent,
}: {
  partId: string
  source?: 'active' | 'demo'
  onBack: () => void
  onOpenComponent: () => void
}) {
  const q = source === 'demo' ? '?source=demo' : ''
  const { data, error, loading } = useApi<ComponentIntelligence>(`/api/components/${encodeURIComponent(partId)}${q}`)

  if (loading) {
    return (
      <div className="page">
        <div className="loadingBand">
          <FileSearch size={24} className="cyanText" style={{ margin: '0 auto 12px' }} />
          Loading Immutable 9-Stage Analytical Trace & Proof…
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="page">
        <div className="error">{error}</div>
      </div>
    )
  }

  if (!data) return null

  const c = data.component
  const exp = data.explanation
  const facts = parseList(exp.facts)
  const findings = parseList(exp.model_findings)
  const policy = parseList(exp.policy_reasoning)
  const counterfactuals = parseList(exp.counterfactuals)
  const dq = data.decision.data_quality || {}
  const supportCount = Number(data.decision.supporting_evidence_count || 0)

  const primaryTrigger = String(data.decision.primary_trigger || 'NOMINAL_SCREENING_PASS')
  const engineeringRec = String(data.decision.engineering_recommendation || 'RELEASE_SAFE')
  const safetyMargin = data.decision.safety_margin || {}
  const oodExp = data.decision.ood_explanation || {}
  const secEv = Array.isArray(data.decision.secondary_evidence) ? data.decision.secondary_evidence : []

  // Ensure all 9 stages are present
  const defaultStages = [
    { stage_number: 1, stage_name: 'DATA', status: 'PASS', summary: 'Telemetry ingested & parsed.' },
    { stage_number: 2, stage_name: 'VALIDATION', status: String(dq.status || 'PASS'), summary: 'Data quality & schema checks.' },
    { stage_number: 3, stage_name: 'FEATURES', status: 'COMPUTED', summary: 'Temporal dynamics & baseline features.' },
    { stage_number: 4, stage_name: 'ANOMALY', status: (c.anomaly_risk ?? 0) >= 0.5 ? 'FLAGGED' : 'PASS', summary: `Module A risk: ${num(c.anomaly_risk, 2)}` },
    { stage_number: 5, stage_name: 'FORECAST', status: (c.failure_risk ?? 0) >= 0.5 || data.decision.near_limit ? 'FLAGGED' : 'PASS', summary: `Module B risk: ${num(c.failure_risk, 2)}` },
    { stage_number: 6, stage_name: 'OOD', status: c.ood_status, summary: `OOD novelty: ${c.ood_status}. (OOD ≠ defect)` },
    { stage_number: 7, stage_name: 'SAFETY_POLICY', status: 'EVALUATED', summary: `Fused risk: ${num(c.risk_score, 2)} vs thresholds.` },
    { stage_number: 8, stage_name: 'HARD_OVERRIDE', status: data.decision.hard_limit_violation ? 'OVERRIDDEN' : 'NO_OVERRIDE', summary: data.decision.hard_limit_violation ? 'Physical limit breached → Forced REJECT' : 'Physical limits preserved.' },
    { stage_number: 9, stage_name: 'FINAL_DECISION', status: c.decision, summary: `Disposition: ${c.decision}` },
  ]

  const rawTrace =
    Array.isArray(data.decision.decision_trace) && data.decision.decision_trace.length === 9
      ? data.decision.decision_trace
      : defaultStages

  const isHardLimitViolated = Boolean(data.decision.hard_limit_violation)

  return (
    <div className="page">
      {/* ============================================================ */}
      {/* PAGE HEADER                                                  */}
      {/* ============================================================ */}
      <div className="pageHead">
        <div>
          <button className="btn ghost" onClick={onBack}>
            <ArrowLeft size={13} /> Back to Component Passport
          </button>
          <div className="eyebrow" style={{ marginTop: 14 }}>
            SCREEN 03 · AUDITABLE EVIDENCE & EXPLAINABILITY
          </div>
          <h1>Engineering Evidence Record</h1>
          <p>
            Persisted analytical decision trace generated by the conservative safety policy. Never synthetic or LLM-fabricated.
          </p>
        </div>

        <div className="actions">
          <StatusBadge decision={c.decision} large />
          <button className="btn primary" onClick={onOpenComponent}>
            <Cpu size={13} /> Digital Passport
          </button>
        </div>
      </div>

      {/* ============================================================ */}
      {/* HERO DISPOSITION & PROVENANCE                                */}
      {/* ============================================================ */}
      <div className="overviewMainGrid" style={{ marginBottom: 18 }}>
        <div className="panel" style={{ padding: 18 }}>
          <div className="smallcaps" style={{ color: 'var(--accent)' }}>
            CERTIFIED FLIGHT SCREENING DISPOSITION
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 10 }}>
            <StatusBadge decision={c.decision} large />
            <span className="mono part" style={{ fontSize: '15px' }}>{c.part_id}</span>
            <span
              className="badge large"
              style={{
                background: engineeringRec.includes('RELEASE') ? 'var(--safe-bg)' : 'var(--review-bg)',
                color: engineeringRec.includes('RELEASE') ? 'var(--safe)' : 'var(--review)',
                borderColor: engineeringRec.includes('RELEASE') ? 'rgba(16, 185, 129, 0.4)' : 'rgba(245, 158, 11, 0.4)',
              }}
            >
              {engineeringRec}
            </span>
          </div>

          <p style={{ fontSize: '11.5px', lineHeight: 1.6, color: 'var(--soft)', margin: '12px 0 0' }}>
            {exp.summary || 'Analytical safety evaluation concluded without manual exceptions.'}
          </p>

          {/* Primary Trigger Callout */}
          <div
            style={{
              marginTop: 14,
              padding: '10px 14px',
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--line2)',
              background: 'rgba(11, 19, 36, 0.8)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}
          >
            <div>
              <span className="smallcaps" style={{ color: 'var(--muted)' }}>PRIMARY DECISION TRIGGER:</span>
              <div
                className="mono"
                style={{
                  fontSize: '12px',
                  fontWeight: 700,
                  marginTop: 2,
                  color: primaryTrigger.includes('HARD')
                    ? 'var(--reject)'
                    : primaryTrigger.includes('OOD')
                    ? 'var(--review)'
                    : 'var(--accent)',
                }}
              >
                {primaryTrigger}
              </div>
            </div>
            <span className="badge safe">Root Cause Logged</span>
          </div>
        </div>

        <div className="panel" style={{ padding: 18, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
          <div className="fact">
            <span className="smallcaps">Combined Risk</span>
            <strong className="mono" style={{ fontSize: '16px', color: 'var(--ink)' }}>
              {num(c.risk_score, 3)}
            </strong>
          </div>
          <div className="fact">
            <span className="smallcaps">System Confidence</span>
            <strong className="mono" style={{ fontSize: '16px', color: 'var(--safe)' }}>
              {c.confidence || 'MODERATE'}
            </strong>
          </div>
          <div className="fact">
            <span className="smallcaps">Support Channels</span>
            <strong className="mono" style={{ fontSize: '16px', color: 'var(--accent)' }}>
              {supportCount} / 5
            </strong>
          </div>
          <div className="fact">
            <span className="smallcaps">Domain Shift</span>
            <strong className="mono" style={{ fontSize: '16px', color: 'var(--review)' }}>
              {c.ood_status}
            </strong>
          </div>
        </div>
      </div>

      {/* ============================================================ */}
      {/* 9-STAGE DECISION TRACE (CENTERPIECE TIMELINE)                 */}
      {/* ============================================================ */}
      <div className="sectionTitle">
        <span>IMMUTABLE 9-STAGE DECISION TRACE</span>
        <span className="smallcaps" style={{ color: 'var(--accent)' }}>
          DATA → VALIDATION → FEATURES → ANOMALY → FORECAST → OOD → SAFETY_POLICY → HARD_OVERRIDE → FINAL_DECISION
        </span>
      </div>

      <div className="decisionTrace nine" style={{ marginBottom: 20 }}>
        {rawTrace.map((st: any, idx: number) => {
          const stNum = st.stage_number || idx + 1
          const stName = st.stage_name || `STAGE ${stNum}`
          const stStatus = String(st.status || 'COMPUTED').toUpperCase()
          const isOverrideStage = stName === 'HARD_OVERRIDE'
          const isViolated = isOverrideStage && stStatus === 'OVERRIDDEN'
          const isLast = idx === rawTrace.length - 1

          let statusCls = 'computed'
          if (stStatus.includes('PASS') || stStatus.includes('NO_OVERRIDE') || stStatus === 'SAFE') {
            statusCls = 'pass'
          } else if (stStatus.includes('FLAG') || stStatus === 'REVIEW' || stStatus === 'MODERATE' || stStatus === 'SEVERE') {
            statusCls = 'flagged'
          } else if (stStatus.includes('OVERRIDDEN') || stStatus === 'REJECT') {
            statusCls = 'reject'
          }

          return (
            <div
              key={idx}
              className={`traceItem ${isViolated ? 'hardOverrideAlert' : ''}`}
              style={{
                borderTop: isLast
                  ? '3px solid var(--accent)'
                  : isViolated
                  ? '3px solid var(--reject)'
                  : '1px solid var(--line)',
              }}
            >
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div className="stageNum">0{stNum}</div>
                  {isViolated && <AlertTriangle size={12} color="var(--reject)" />}
                </div>
                <div className={`stageStatus ${statusCls}`}>{stStatus}</div>
                <h3 style={{ color: 'var(--ink)' }}>{stName}</h3>
                <p style={{ color: 'var(--muted)', marginTop: 6 }}>{st.summary}</p>
              </div>

              <div style={{ fontSize: '7.5px', color: 'var(--dim)', borderTop: '1px solid var(--line)', paddingTop: 6, marginTop: 8 }}>
                {st.stage_name === 'OOD' ? (
                  <span>OOD ≠ Defect</span>
                ) : st.stage_name === 'HARD_OVERRIDE' ? (
                  <span style={{ color: isViolated ? 'var(--reject)' : 'var(--safe)' }}>
                    {isViolated ? 'Forced REJECT' : 'Limits OK'}
                  </span>
                ) : (
                  <span>Stage {stNum} Verified</span>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {/* ============================================================ */}
      {/* SECONDARY EVIDENCE & SAFETY POLICY JUSTIFICATION             */}
      {/* ============================================================ */}
      <div className="overviewMainGrid" style={{ marginBottom: 18 }}>
        {/* Secondary Corroborating Evidence */}
        <div className="panel">
          <div className="panelHead">
            <div className="panelTitle">
              <Layers size={14} color="var(--accent)" />
              <span>Secondary Corroborating Evidence Channels</span>
            </div>
            <span className="smallcaps" style={{ color: 'var(--muted)' }}>
              {secEv.length} INDEPENDENT SIGNALS
            </span>
          </div>
          <div className="panelBody">
            {secEv.length > 0 ? (
              <ul className="evidenceList" style={{ margin: 0, paddingLeft: 18 }}>
                {secEv.map((ev: string, i: number) => (
                  <li key={i} style={{ color: 'var(--soft)', fontSize: '11px', marginBottom: 8 }}>
                    {ev}
                  </li>
                ))}
              </ul>
            ) : (
              <div style={{ fontSize: '11px', color: 'var(--muted)' }}>
                No secondary anomalies or boundary warnings observed outside the primary channel.
              </div>
            )}
          </div>
        </div>

        {/* Quantified Safety Margin Evaluation */}
        <div className="panel">
          <div className="panelHead">
            <div className="panelTitle">
              <ShieldCheck size={14} color="var(--safe)" />
              <span>Safety Margin & Physical Boundaries</span>
            </div>
            <span className={`badge ${safetyMargin.status === 'VIOLATED' ? 'reject' : safetyMargin.status === 'NEAR_LIMIT' ? 'review' : 'safe'}`}>
              {safetyMargin.status || 'NOMINAL'}
            </span>
          </div>
          <div className="panelBody">
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 12 }}>
              <div className="fact">
                <span className="smallcaps">Absolute Safety Margin</span>
                <strong className="mono">
                  {safetyMargin.absolute_margin != null ? `${num(safetyMargin.absolute_margin, 3)} ${c.unit}` : '—'}
                </strong>
              </div>
              <div className="fact">
                <span className="smallcaps">Relative Buffer</span>
                <strong className="mono" style={{ color: safetyMargin.status === 'VIOLATED' ? 'var(--reject)' : 'var(--safe)' }}>
                  {safetyMargin.relative_margin_pct != null ? `${num(safetyMargin.relative_margin_pct, 1)}%` : '—'}
                </strong>
              </div>
            </div>
            <div style={{ fontSize: '10px', color: 'var(--muted)', lineHeight: 1.5 }}>
              {safetyMargin.interpretation || 'Operating safely within engineering limits.'}
            </div>
          </div>
        </div>
      </div>

      {/* ============================================================ */}
      {/* COUNTERFACTUAL SENSITIVITY & SAFETY RESTRAINT                */}
      {/* ============================================================ */}
      <div className="overviewMainGrid">
        <div className="panel">
          <div className="panelHead">
            <div className="panelTitle">
              <Shield size={14} color="var(--review)" />
              <span>Safety Restraint: Why Not Automatic Reject?</span>
            </div>
            <span className="smallcaps">Defensive Architecture</span>
          </div>
          <div className="panelBody">
            <ul className="evidenceList" style={{ margin: 0, paddingLeft: 18 }}>
              {c.decision === 'REVIEW' ? (
                <>
                  <li style={{ color: 'var(--soft)', fontSize: '10.5px' }}>
                    Current evidence does not meet the autonomous non-negotiable rejection boundary.
                  </li>
                  <li style={{ color: 'var(--soft)', fontSize: '10.5px' }}>
                    {isHardLimitViolated
                      ? 'A hard engineering limit violation is present and was flagged.'
                      : 'Authoritative physical engineering limits remain unbreached in observed telemetry.'}
                  </li>
                  <li style={{ color: 'var(--soft)', fontSize: '10.5px' }}>
                    OOD domain novelty was treated strictly as epistemic uncertainty, not automatically assumed as a defect.
                  </li>
                </>
              ) : c.decision === 'SAFE' ? (
                <>
                  <li style={{ color: 'var(--soft)', fontSize: '10.5px' }}>
                    Zero hard limit violations and no material corroborated anomaly signals were detected.
                  </li>
                  <li style={{ color: 'var(--soft)', fontSize: '10.5px' }}>
                    The system does not elevate a component to scrap or review without independent evidence channels.
                  </li>
                </>
              ) : (
                <li style={{ color: 'var(--soft)', fontSize: '10.5px' }}>
                  Unconditional rejection is warranted by verified hard limit violations or multi-channel risk consensus.
                </li>
              )}
            </ul>
          </div>
        </div>

        <div className="panel">
          <div className="panelHead">
            <div className="panelTitle">
              <Zap size={14} color="var(--accent)" />
              <span>Counterfactual Sensitivity: What Would Change Decision?</span>
            </div>
            <span className="smallcaps">Sensitivity Analysis</span>
          </div>
          <div className="panelBody">
            <ul className="evidenceList" style={{ margin: 0, paddingLeft: 18 }}>
              {(counterfactuals.length
                ? counterfactuals
                : [exp.specific_counterfactual || 'No single telemetry shift is sufficient to alter the safety boundary.']
              ).map((x, i) => (
                <li key={i} style={{ color: 'var(--soft)', fontSize: '10.5px', marginBottom: 6 }}>
                  {x}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="fact">
      <span className="smallcaps">{label}</span>
      <strong className="mono" style={{ fontSize: '14px', color: 'var(--ink)' }}>
        {value}
      </strong>
    </div>
  )
}
